### ISSUE TITLE
Fixing workflow test

### ISSUE THREAD

**Issue by MrGKanev** [Bimbalacom/bimbalacom#68]
After initializing the tests which were off from the start of the repo, we still can't get the green checkmark. (my bad) It will be a good idea to check what kind of problems are there and fix them.

**Comment by l-alexandrov** [comment]
We are getting the database created, but it is empty. In order to fix this we will need to preseed it.

**Comment by MrGKanev** [comment]
The action is stopped temporarily until we have more free time for fixing it.

**Comment by l-alexandrov** [comment]
We are now having a green check mark for the the CD, but we still don't have a CI with tests running.
